name: BTRemote
options:
  bundleIdPrefix: io.github.jqssun
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true
  groupSortPosition: top
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    ENABLE_PREVIEWS: YES
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: "0.0.1"
    CURRENT_PROJECT_VERSION: "1"

targets:
  BTRemote:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: BTRemote
    resources:
      - BTRemote/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.github.jqssun.btremote
        TARGETED_DEVICE_FAMILY: "1"
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: BTRemote/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
schemes:
  BTRemote:
    build:
      targets:
        BTRemote: all
    run:
      config: Debug
    archive:
      config: Release
